### ISSUE TITLE
Build out Design Principles

### ISSUE THREAD

**Issue by adammontville** [CISecurity/oval-governance-update#27]
The purpose of a set of design principles is to provide proposers some guardrails around the boundaries of the language itself. Such boundaries may differ between major versions, though that in itself may end up being a design principle. See #7 for the existing conversation.

**Comment by DavidRies** [comment]
Here are a few ideas gleaned from feedback existing docs to get us started...

## High-Level

- Capabilities should not require changes to scanned systems in order to implement (e.g. be read-only)
- Changes should not impose security issues
- Changes should not result in inconsistency
- Changes should not require obsoleted technologies or methodologies
- Changes should not require the use of undocumented APIs
- Changes should not duplicate existing capabilities unless there is a compelling reason to do so (e.g. major simplification), in which case they should be designed to allow for the deprecation and ultimate replacement of the constructs that are duplicated
- OVAL capabilities should fit into the OVAL use cases
- Capabilities should not dictate implementation, but should document at least one practical implementation method

## Construct-Specific

- An OVAL Item must model the posture attribute data being collected off an endpoint
- An OVAL Item must NOT combine multiple system-level structures
- OVAL Items SHOULD only include the OVAL Entities that the community requires
- An OVAL Object SHOULD include the minimum set of OVAL Entities needed to uniquely identify an OVAL Item collected from an endpoint

## Mechanics (naming, versioning, etc.)

- Changes should not break backwards compatibility within their major version (i.e. 5.x, 6.x, etc.)
- OVAL constructs must conform to naming conventions (http://ovalproject.github.io/getting-started/best-practices/#4-naming-conventions)
- OVAL constructs must follow the versioning policy

**Comment by DavidRies** [comment]
Feedback from call: we need wider feedback on and contribution to this doc; we should consider a process whereby if/when there is consensus that a proposal is undesirable even though it does not conflict with a design principle, a new design principle can be adopted by the community and used as the basis for an objection. Obviously, this could be abused, but if it is handled openly and reasonably, then it should be a positive way for the community to further define its shared values and help ensure that OVAL reflects them.

**Comment by adammontville** [comment]
I like this approach. It allows us to define the design principles we can and doesn't force us into poor definitions for the things we believe are design principles, but, for one reason or another, have a hard time articulating at the moment. 

I think we can take this type of approach across our process generally. Where there are gates in the process with selection criteria, we might consider having a learning mechanism that can update/alter that selection criteria as we practice going through the process (see newly created issue #34 ).

**Comment by Randal-Taylor** [comment]
This approach seems fine to me.  However, it seems like there should be a option for the proposal to be modified to NOT violate design principles.  IOW, the Area Supervisor says the proposal violates design principles but would not violate them if it was modified in a certain way.  Is that feedback-->modification loop possible or are we suggesting the initial proposal be rejected and a new one be proposed that includes the suggested change(s)?

**Comment by adammontville** [comment]
My understanding - someone correct me if I'm wrong - is that if there's a design principle violation, the proposal would need to be reworked. This mechanism is intended to consider design principles we have been, to date, unable to articulate for one reason or another. This way, we have a reasonable set of design principles to start, but can add new ones as we go without trying to think of everything ahead of time.

**Comment by DavidRies** [comment]
The current process offers a mechanism to modify a rejected proposal along these lines:

1. An Issue is created describing the reason for the schema change, etc. 
2. A Proposal is made that addresses the Issue
3. Community members can offer feedback, collaborate on the Proposal, Object to a Proposal, and/or offer Alternate Proposals that address the Issue
4. If a Proposal is Objected to and rejected, the Issue (and any existing Alternate Proposals) would remain. The Proposal author could revise their rejected Proposal and resubmit it as a new Alternate Proposal for the Issue.

Does that make sense, seem reasonable etc.? Basically you can just revise a rejected Proposal and resubmit it as an "Alternate Proposal".

**Comment by Randal-Taylor** [comment]
I think that will work.  It allows us to capture rejected proposals for historical purposes and still accept a modified versions of proposals.

**Comment by adammontville** [comment]
I'd like to suggest that we use RFC 2119 language here also (we should consider doing this across the board, actually).

I'm not seeing a bunch of objections to taking the approach of defining an initial set of principles that can be modified as we learn. @DavidRies would you be able to pull the pertinent pieces of this thread into something more concrete?

**Comment by adammontville** [comment]
Updated [design principles artifact](https://github.com/CISecurity/oval-governance-update/blob/master/process_artifacts/design_principles.md) with information in this thread. Please review and post objections no later than December 8.

**Comment by adammontville** [comment]
Closing: No objections received.
